server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: ms-venta

#  datasource:
 #   url: jdbc:mysql://localhost:3306/ms-venta
  #  username: root
   # password: root
    #driver-class-name: com.mysql.cj.jdbc.Driver

    datasource:
      url: jdbc:h2:mem:ms-venta
      driver-class-name: org.h2.Driver
      username: sa
      password: password
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
      h2:
        console:
          enabled: true
          path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost